export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_USER = 'SET_USER'
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const ADD_TO_CART = "ADD_TO_CART"
export const SET_ORDER_DETAILS = "SET_ORDER_DETAILS"
export const SET_ORDER_HISTORY = "SET_ORDER_HISTORY"

export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR'
export const TOGGLE_CART = 'TOGGLE_CART'
export const TOGGLE_CONFIRMATION_BOX = 'TOGGLE_CONFIRMATION_BOX'

export const INCREASE_PRODUCT_AMOUNT = "INCREASE_PRODUCT_AMOUNT"
export const DECREASE_PRODUCT_AMOUNT = "DECREASE_PRODUCT_AMOUNT"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"
export const CLEAR_CURRENT_ORDER = "CLEAR_CURRENT_ORDER"
export const ADD_CURRENT_ORDER_TO_USER_HISTORY = "ADD_CURRENT_ORDER_TO_USER_HISTORY"
export const SET_COUNTDOWN = "SET_COUNTDOWN"